mklink /J "%HOMEDRIVE%%HOMEPATH%\Documents\Paradox Interactive\Crusader Kings II\mod\WTWSMS" ".\WTWSMS"
mklink /J "%HOMEDRIVE%%HOMEPATH%\Documents\Paradox Interactive\Crusader Kings II\mod\WTWSMS_AfricanPortraits" ".\WTWSMS_AfricanPortraits"
mklink /J "%HOMEDRIVE%%HOMEPATH%\Documents\Paradox Interactive\Crusader Kings II\mod\WTWSMS_CelticPortraits" ".\WTWSMS_CelticPortraits"
mklink /J "%HOMEDRIVE%%HOMEPATH%\Documents\Paradox Interactive\Crusader Kings II\mod\WTWSMS_NorsePortraits" ".\WTWSMS_NorsePortraits"
mklink /J "%HOMEDRIVE%%HOMEPATH%\Documents\Paradox Interactive\Crusader Kings II\mod\WTWSMS_TurkishAndCelticPortraits" ".\WTWSMS_TurkishAndCelticPortraits"
mklink /J "%HOMEDRIVE%%HOMEPATH%\Documents\Paradox Interactive\Crusader Kings II\mod\WTWSMS_MediterraneanPortraits" ".\WTWSMS_MediterraneanPortraits"
mklink /J "%HOMEDRIVE%%HOMEPATH%\Documents\Paradox Interactive\Crusader Kings II\mod\WTWSMS_Font" ".\WTWSMS_Font"
mklink /J "%HOMEDRIVE%%HOMEPATH%\Documents\Paradox Interactive\Crusader Kings II\mod\WTWSMS_French" ".\WTWSMS_French"
mklink /J "%HOMEDRIVE%%HOMEPATH%\Documents\Paradox Interactive\Crusader Kings II\mod\WtWSMS_EBS" ".\WtWSMS_EBS"
pause